name: pofo_web
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.2

  flutter_bloc: ^9.1.0
  http: ^1.3.0
  flutter_svg: ^2.0.17
  sizer: ^3.0.5
  # connectivity_plus: ^6.1.3
  connectivity_plus: ^5.0.2
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  animated_text_kit: ^4.2.3
  scrollable_positioned_list: ^0.3.8
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/icons/
    - assets/gif/

  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat.ttf
     
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
